spring.application.name=hostel-management-system

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mec_hostel_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=hostel_user
spring.datasource.password=hostel_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# spring.datasource.url=jdbc:h2:mem:hostel_db
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=false

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=mec-hostel-management-super-secret-key-2026
jwt.expiration=86400000
